app:
  baseUrl: https://backstage.openmsa.monster

backend:
  baseUrl: https://backstage.openmsa.monster
  listen: ':7007'
  cors:
    origin: https://backstage.openmsa.monster
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
    
  database:
    client: pg
    #connection: ${DATABASE_URL}
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

catalog:
  locations:
    - type: url
      target: https://github.com/evelyn0410/backstage-custom/blob/main/catalog-entities/all.yaml
    # - type: url
    #   target: https://github.com/evelyn0410/backstage-custom/blob/main/catalog-entities/entities.yaml
    - type: url
      target: https://github.com/evelyn0410/backstage-custom/blob/main/catalog-entities/org.yaml
      rules:
        - allow: [User, Group]
    # - type: url
    #   target: https://github.com/evelyn0410/backstage/blob/master/packages/catalog-model/examples/all.yaml
    # - type: url
    #   target: https://github.com/evelyn0410/janus-software-templates/blob/main/showcase-templates.yaml