site_name: 'Backstage Custom'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/evelyn0410/backstage-custom
edit_uri: edit/main/docs

plugins:
  - techdocs-core