---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: evelyn.park
spec:
  memberOf: [team-devops,team-arch,team-develop]
  profile:
    displayName: evelyn.park
    email: evelyn.park@osckorea.com
    picture: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReFC5NabcURirwrI8zlll87J2VVB_9Sn2RjQ&usqp=CAU