name: Docker Build
description: Docker Build
inputs:
  password:
    description: The password to use for the registry
    required: true
  username:
    description: The username to use for the registry
    required: true
  imageName:
    description: The name of the image to build
    required: true
  imageTags:
    description: The tags to apply to the image
    required: false
  imageLabels:
    description: The labels for the Docker image
    required: false
  push:
    description: Whether to push the image
    required: true

runs:
  using: composite
    steps:
      # 도커 빌드 관련 셋업
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 도커 로그인
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.imageName }}
          tags: |
            ${{ inputs.imageTags }}
          labels: |
            ${{ inputs.imageLabels }}

      # 도커이미지 빌드하고 허브로 푸쉬
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        shell: bash
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache