version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backstage:
    image: jei0486/backstage
    restart: always
    ports:
      - 7007:7007
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_GITHUB_CLIENT_ID=${AUTH_GITHUB_CLIENT_ID}
      - AUTH_GITHUB_CLIENT_SECRET=${AUTH_GITHUB_CLIENT_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_TOKEN=${JENKINS_TOKEN}
      - SONARQUBE_URL=${SONARQUBE_URL}
      - SONARQUBE_TOKEN=${SONARQUBE_TOKEN}
      - NEXUS_REPOSITORY_MANAGER_URL=${NEXUS_REPOSITORY_MANAGER_URL}
      - NEXUS_REPOSITORY_MANAGER_AUTH=${NEXUS_REPOSITORY_MANAGER_AUTH}
      - ARGOCD_URL=${ARGOCD_URL}
      - ARGOCD_AUTH_TOKEN=${ARGOCD_AUTH_TOKEN}
      - K8S_MINIKUBE_URL=${K8S_MINIKUBE_URL}
      - K8S_MINIKUBE_TOKEN=${K8S_MINIKUBE_TOKEN}
      - K8S_KIND_URL=${K8S_KIND_URL}
      - K8S_KIND_TOKEN=${K8S_KIND_TOKEN}
      - K8S_K3S_URL=${K8S_K3S_URL}
      - K8S_K3S_TOKEN=${K8S_K3S_TOKEN}
      - NODE_ENV=development
